var data = [{"ID":3,"Name":"Aboleth","HD":9,"PAGE":14,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":2}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":94,"Name":"Adherer","HD":4,"PAGE":15,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":11},{"ID":10}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":84,"Name":"Aghul","HD":7,"PAGE":55,
"source":{"ID":2,"Name":"Tome of the Unclean 1st Printing","ShortName":"ToU"},
"qualities":[{"ID":3},{"ID":22}],
"terrains":[{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":3},
{"ID":95,"Name":"Algoid","HD":5,"PAGE":19,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":1},{"ID":5},{"ID":8}],
"types":[{"ID":14}],
"SingleFrequency":1},
{"ID":4,"Name":"Allip","HD":4,"PAGE":20,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":6},{"ID":21}],
"terrains":[{"ID":11},{"ID":7},{"ID":1},{"ID":4},{"ID":8},{"ID":10}],
"types":[{"ID":16}],
"SingleFrequency":3},
{"ID":181,"Name":"Amnug","HD":2,"PAGE":9,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":38},{"ID":21}],
"terrains":[{"ID":11},{"ID":9},{"ID":7},{"ID":1},{"ID":4},{"ID":8},{"ID":10},{"ID":5}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":327,"Name":"Androphagos","HD":6,"PAGE":22,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":4}],
"terrains":[{"ID":4},{"ID":9}],
"types":[{"ID":11}],
"SingleFrequency":3},
{"ID":337,"Name":"Animated Armor","HD":5,"PAGE":19,
"source":{"ID":10,"Name":"Dungeons & Dragons Monster Manual 5e","ShortName":"MM"},
"qualities":[{"ID":37}],
"terrains":[{"ID":12},{"ID":11},{"ID":10},{"ID":8},{"ID":1},{"ID":9},{"ID":7},{"ID":3},{"ID":6},{"ID":13},{"ID":4},{"ID":5}],
"types":[{"ID":4}],
"SingleFrequency":3},
{"ID":6,"Name":"Ankheg","HD":5,"PAGE":21,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":5}],
"types":[{"ID":3}],
"SingleFrequency":2},
{"ID":164,"Name":"Ant Lion","HD":8,"PAGE":23,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":36},{"ID":22}],
"terrains":[{"ID":3},{"ID":7}],
"types":[{"ID":3}],
"SingleFrequency":1},
{"ID":5,"Name":"Ant, giant","HD":3,"PAGE":22,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20}],
"terrains":[{"ID":3},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":8},{"ID":5}],
"types":[{"ID":17}],
"SingleFrequency":1},
{"ID":135,"Name":"Aothsil","HD":1,"PAGE":11,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":17},{"ID":20}],
"terrains":[{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":7,"Name":"Ape, Great","HD":3,"PAGE":23,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":null,"types":[{"ID":2}],
"SingleFrequency":2},
{"ID":165,"Name":"Apparition","HD":8,"PAGE":23,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":11},{"ID":12},{"ID":10}],
"types":[{"ID":16}],
"SingleFrequency":3},
{"ID":287,"Name":"Aranea","HD":3,"PAGE":19,
"source":{"ID":14,"Name":"D&D 3e Monster Manual - First Printing","ShortName":"MM3"},
"qualities":[{"ID":22}],
"terrains":[{"ID":9},{"ID":5}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":349,"Name":"Arimaspi","HD":7,"PAGE":24,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":6},{"ID":4}],
"types":[{"ID":12}],
"SingleFrequency":2},
{"ID":97,"Name":"Assad","HD":1,"PAGE":25,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":4},{"ID":20}],
"terrains":[{"ID":3},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":8}],
"types":[{"ID":11}],
"SingleFrequency":3},
{"ID":9,"Name":"Assassin Vine","HD":5,"PAGE":25,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":21},{"ID":20}],
"terrains":[{"ID":1},{"ID":8},{"ID":9}],
"types":[{"ID":14}],
"SingleFrequency":1},
{"ID":288,"Name":"Athach","HD":14,"PAGE":21,
"source":{"ID":14,"Name":"D&D 3e Monster Manual - First Printing","ShortName":"MM3"},
"qualities":[{"ID":26},{"ID":37},{"ID":22}],
"terrains":[{"ID":13},{"ID":4}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":345,"Name":"Attercrope","HD":1,"PAGE":125,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21},{"ID":45}],
"terrains":[{"ID":9},{"ID":13},{"ID":4}],
"types":[{"ID":8}],
"SingleFrequency":1},
{"ID":295,"Name":"Aurumvorax","HD":12,"PAGE":27,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":7},{"ID":13},{"ID":4}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":98,"Name":"Babbler","HD":5,"PAGE":29,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":1},{"ID":8}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":10,"Name":"Banshee","HD":7,"PAGE":32,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":6},{"ID":21}],
"terrains":[{"ID":3},{"ID":8},{"ID":9}],
"types":[{"ID":16}],
"SingleFrequency":3},
{"ID":11,"Name":"Basilisk","HD":6,"PAGE":33,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":3},{"ID":9},{"ID":7},{"ID":13},{"ID":4}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":191,"Name":"Bat, Giant","HD":2,"PAGE":58,
"source":{"ID":5,"Name":"Basic Fantasy Core Rulebook 3rd Edition","ShortName":"BF"},
"qualities":[{"ID":20}],
"terrains":[{"ID":4},{"ID":5},{"ID":13}],
"types":[{"ID":2}],
"SingleFrequency":1},
{"ID":296,"Name":"Bauk","HD":3,"PAGE":34,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20}],
"terrains":[{"ID":5}],
"types":[{"ID":10}],
"SingleFrequency":2},
{"ID":148,"Name":"Bear","HD":6,"PAGE":35,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":6},{"ID":9},{"ID":7},{"ID":13},{"ID":4},{"ID":5}],
"types":[{"ID":2}],
"SingleFrequency":1},
{"ID":85,"Name":"Bearded Devil","HD":6,"PAGE":61,
"source":{"ID":2,"Name":"Tome of the Unclean 1st Printing","ShortName":"ToU"},
"qualities":[{"ID":3},{"ID":21},{"ID":26}],
"terrains":[{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":3},
{"ID":297,"Name":"Becolaep","HD":4,"PAGE":36,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":10}],
"types":[{"ID":16}],
"SingleFrequency":3},
{"ID":317,"Name":"Bee, Giant","HD":3,"PAGE":206,
"source":{"ID":14,"Name":"D&D 3e Monster Manual - First Printing","ShortName":"MM3"},
"qualities":[{"ID":21},{"ID":4}],
"terrains":[{"ID":7},{"ID":13},{"ID":3}],
"types":[{"ID":17}],
"SingleFrequency":1},
{"ID":192,"Name":"Beetle, Tiger","HD":3,"PAGE":60,
"source":{"ID":5,"Name":"Basic Fantasy Core Rulebook 3rd Edition","ShortName":"BF"},
"qualities":[{"ID":20}],
"terrains":[{"ID":1},{"ID":5}],
"types":[{"ID":17}],
"SingleFrequency":1},
{"ID":252,"Name":"Beholder","HD":15,"PAGE":24,
"source":{"ID":14,"Name":"D&D 3e Monster Manual - First Printing","ShortName":"MM3"},
"qualities":[{"ID":26},{"ID":4},{"ID":37},{"ID":22}],
"terrains":[{"ID":6},{"ID":11},{"ID":10},{"ID":5}],
"types":[{"ID":11}],
"SingleFrequency":3},
{"ID":12,"Name":"Belker","HD":7,"PAGE":37,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":2},{"ID":4},{"ID":6},{"ID":22}],
"terrains":[{"ID":12}],
"types":[{"ID":6}],
"SingleFrequency":3},
{"ID":313,"Name":"Bisytsia","HD":4,"PAGE":39,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":2},{"ID":20}],
"terrains":[{"ID":11},{"ID":9},{"ID":7},{"ID":4},{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":3},
{"ID":161,"Name":"Black Pudding","HD":10,"PAGE":238,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":11},{"ID":1},{"ID":10},{"ID":5},{"ID":8}],
"types":[{"ID":13}],
"SingleFrequency":2},
{"ID":281,"Name":"Blade Spirit","HD":9,"PAGE":11,
"source":{"ID":6,"Name":"Basic Fantasy Field Guide","ShortName":"BFFG"},
"qualities":[{"ID":37},{"ID":6}],
"terrains":[{"ID":11},{"ID":10}],
"types":[{"ID":4}],
"SingleFrequency":3},
{"ID":254,"Name":"Blight","HD":4,"PAGE":31,
"source":{"ID":10,"Name":"Dungeons & Dragons Monster Manual 5e","ShortName":"MM"},
"qualities":[{"ID":21},{"ID":45}],
"terrains":[{"ID":9},{"ID":1},{"ID":8}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":266,"Name":"Blood Rose","HD":2,"PAGE":61,
"source":{"ID":5,"Name":"Basic Fantasy Core Rulebook 3rd Edition","ShortName":"BF"},
"qualities":[{"ID":27},{"ID":20}],
"terrains":[{"ID":8}],
"types":[{"ID":14}],
"SingleFrequency":1},
{"ID":99,"Name":"Bloodsucking Wyrm","HD":6,"PAGE":42,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":7},{"ID":22}],
"terrains":[{"ID":2},{"ID":5},{"ID":9}],
"types":[{"ID":3}],
"SingleFrequency":1},
{"ID":149,"Name":"Boar","HD":2,"PAGE":43,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":7},{"ID":9},{"ID":13}],
"types":[{"ID":2}],
"SingleFrequency":1},
{"ID":350,"Name":"Bolotnyi","HD":7,"PAGE":46,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21},{"ID":7}],
"terrains":[{"ID":8}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":282,"Name":"Bone Horror","HD":4,"PAGE":13,
"source":{"ID":6,"Name":"Basic Fantasy Field Guide","ShortName":"BFFG"},
"qualities":[{"ID":37},{"ID":21}],
"terrains":[{"ID":11},{"ID":12},{"ID":10}],
"types":[{"ID":4}],
"SingleFrequency":1},
{"ID":13,"Name":"Bugbear","HD":3,"PAGE":48,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":45}],
"terrains":[{"ID":6},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":8},{"ID":5}],
"types":[{"ID":10}],
"SingleFrequency":2},
{"ID":346,"Name":"Buggane","HD":6,"PAGE":127,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":45},{"ID":20}],
"terrains":[{"ID":9},{"ID":3},{"ID":14},{"ID":7},{"ID":13},{"ID":1},{"ID":4},{"ID":5}],
"types":[{"ID":8}],
"SingleFrequency":1},
{"ID":329,"Name":"Bukavak","HD":5,"PAGE":49,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":14},{"ID":15}],
"types":[{"ID":3}],
"SingleFrequency":1},
{"ID":150,"Name":"Bulette","HD":9,"PAGE":49,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":36},{"ID":22}],
"terrains":[{"ID":3},{"ID":7},{"ID":13}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":298,"Name":"Cadaver Caterpillar","HD":3,"PAGE":50,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":9},{"ID":1},{"ID":8},{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":166,"Name":"Cave Fisher","HD":3,"PAGE":53,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":17}],
"terrains":[{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":100,"Name":"Centipede, Giant","HD":3,"PAGE":53,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":8},{"ID":5}],
"types":[{"ID":17}],
"SingleFrequency":1},
{"ID":300,"Name":"Cerberus","HD":5,"PAGE":54,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":37},{"ID":22}],
"terrains":[{"ID":12}],
"types":[{"ID":11}],
"SingleFrequency":3},
{"ID":318,"Name":"Chawl Witch","HD":4,"PAGE":55,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21},{"ID":25}],
"terrains":[{"ID":8}],
"types":[{"ID":10}],
"SingleFrequency":3},
{"ID":14,"Name":"Chimera","HD":9,"PAGE":57,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":1},{"ID":3},{"ID":4},{"ID":7},{"ID":8},{"ID":9},{"ID":13}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":289,"Name":"Choker","HD":3,"PAGE":36,
"source":{"ID":14,"Name":"D&D 3e Monster Manual - First Printing","ShortName":"MM3"},
"qualities":[{"ID":17},{"ID":20}],
"terrains":[{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":351,"Name":"Chort","HD":6,"PAGE":57,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":2},{"ID":37}],
"terrains":[{"ID":12},{"ID":5},{"ID":11}],
"types":[{"ID":7}],
"SingleFrequency":3},
{"ID":255,"Name":"Chuul","HD":11,"PAGE":36,
"source":{"ID":14,"Name":"D&D 3e Monster Manual - First Printing","ShortName":"MM3"},
"qualities":[{"ID":22}],
"terrains":[{"ID":3},{"ID":9},{"ID":7},{"ID":8}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":319,"Name":"Clubnek","HD":2,"PAGE":60,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21},{"ID":40}],
"terrains":[{"ID":7}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":151,"Name":"Cockatrice","HD":5,"PAGE":60,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20},{"ID":40}],
"terrains":[{"ID":9},{"ID":7},{"ID":13}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":167,"Name":"Coffer Corpse","HD":2,"PAGE":60,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":11},{"ID":10},{"ID":5}],
"types":[{"ID":16}],
"SingleFrequency":1},
{"ID":152,"Name":"Couatl","HD":9,"PAGE":61,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":1},{"ID":9},{"ID":7}],
"types":[{"ID":7}],
"SingleFrequency":3},
{"ID":315,"Name":"Crab, Giant","HD":3,"PAGE":62,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":null,
"terrains":[{"ID":14},{"ID":15},{"ID":2}],
"types":[{"ID":17}],
"SingleFrequency":1},
{"ID":15,"Name":"Crocodile","HD":3,"PAGE":63,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":7},{"ID":21}],
"terrains":[{"ID":1},{"ID":8}],
"types":[{"ID":2}],
"SingleFrequency":1},
{"ID":207,"Name":"Crypt Dweller","HD":2,"PAGE":21,
"source":{"ID":6,"Name":"Basic Fantasy Field Guide","ShortName":"BFFG"},
"qualities":[{"ID":21}],
"terrains":[{"ID":10}],
"types":[{"ID":16}],
"SingleFrequency":3},
{"ID":101,"Name":"Crypt Thing","HD":6,"PAGE":63,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":6},{"ID":21}],
"terrains":[{"ID":10}],
"types":[{"ID":16}],
"SingleFrequency":3},
{"ID":168,"Name":"Crysmal","HD":6,"PAGE":64,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20}],
"terrains":[{"ID":5}],
"types":[{"ID":7}],
"SingleFrequency":2},
{"ID":102,"Name":"Cyclops","HD":5,"PAGE":64,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":4},{"ID":5},{"ID":14},{"ID":7},{"ID":13}],
"types":[{"ID":9}],
"SingleFrequency":2},
{"ID":136,"Name":"Dakmour Wyrm","HD":6,"PAGE":23,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":44},{"ID":22}],
"terrains":[{"ID":1},{"ID":8},{"ID":9}],
"types":[{"ID":5}],
"SingleFrequency":3},
{"ID":16,"Name":"Darkmantal","HD":1,"PAGE":67,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":17},{"ID":20}],
"terrains":[{"ID":11},{"ID":10},{"ID":5}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":347,"Name":"Dearg Du","HD":4,"PAGE":128,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":11},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":4},{"ID":10},{"ID":5},{"ID":8},{"ID":3},{"ID":14},{"ID":12}],
"types":[{"ID":8}],
"SingleFrequency":1},
{"ID":103,"Name":"Death Dog","HD":2,"PAGE":68,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":1},{"ID":3},{"ID":4},{"ID":5},{"ID":7},{"ID":8},{"ID":9}],
"types":[{"ID":3}],
"SingleFrequency":1},
{"ID":104,"Name":"Death Knight","HD":9,"PAGE":68,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21},{"ID":26}],
"terrains":[{"ID":1},{"ID":3},{"ID":4},{"ID":5},{"ID":6},{"ID":7},{"ID":8},{"ID":9}],
"types":[{"ID":16}],
"SingleFrequency":2},
{"ID":105,"Name":"Derro","HD":3,"PAGE":69,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20},{"ID":45}],
"terrains":[{"ID":5}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":208,"Name":"Desert Worm","HD":4,"PAGE":25,
"source":{"ID":6,"Name":"Basic Fantasy Field Guide","ShortName":"BFFG"},
"qualities":[{"ID":36},{"ID":22}],
"terrains":[{"ID":3}],
"types":[{"ID":17}],
"SingleFrequency":1},
{"ID":106,"Name":"Devil Dog","HD":6,"PAGE":70,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":6}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":107,"Name":"Dire Corby","HD":2,"PAGE":72,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":40}],
"terrains":[{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":108,"Name":"Doombat","HD":6,"PAGE":74,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":4},{"ID":21}],
"terrains":[{"ID":7}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":153,"Name":"Doppelganger","HD":4,"PAGE":75,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":11},{"ID":9},{"ID":7},{"ID":1},{"ID":4},{"ID":8}],
"types":[{"ID":15}],
"SingleFrequency":3},
{"ID":301,"Name":"Dragonet","HD":4,"PAGE":75,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":44},{"ID":21}],
"terrains":[{"ID":9},{"ID":13},{"ID":4}],
"types":[{"ID":5}],
"SingleFrequency":3},
{"ID":209,"Name":"Draugr","HD":9,"PAGE":88,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":26},{"ID":37},{"ID":21}],
"terrains":[{"ID":10}],
"types":[{"ID":16}],
"SingleFrequency":1},
{"ID":169,"Name":"Drelb","HD":5,"PAGE":88,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":37},{"ID":21}],
"terrains":[{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":1},
{"ID":79,"Name":"Dretch","HD":2,"PAGE":26,
"source":{"ID":2,"Name":"Tome of the Unclean 1st Printing","ShortName":"ToU"},
"qualities":[{"ID":2},{"ID":20}],
"terrains":[{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":1},
{"ID":17,"Name":"Drider","HD":7,"PAGE":89,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":11},{"ID":9},{"ID":1},{"ID":8},{"ID":10},{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":3},
{"ID":18,"Name":"Dryad","HD":2,"PAGE":90,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":9}],
"types":[{"ID":8}],
"SingleFrequency":3},
{"ID":109,"Name":"Duergar","HD":1,"PAGE":88,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20},{"ID":45}],
"terrains":[{"ID":5}],
"types":[{"ID":16}],
"SingleFrequency":1},
{"ID":110,"Name":"Dune Wraith","HD":6,"PAGE":91,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":3}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":111,"Name":"Elemental","HD":5,"PAGE":95,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":1},{"ID":2},{"ID":3},{"ID":4},{"ID":5},{"ID":6},{"ID":7},{"ID":8},{"ID":9},{"ID":14},{"ID":15},{"ID":12},{"ID":11},{"ID":13},{"ID":10}],
"types":[{"ID":6}],
"SingleFrequency":2},
{"ID":182,"Name":"Erder Wyrm","HD":4,"PAGE":76,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":22}],
"terrains":[{"ID":9},{"ID":1},{"ID":4},{"ID":8}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":19,"Name":"Ettercap","HD":5,"PAGE":109,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":9},{"ID":1},{"ID":8},{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":20,"Name":"Ettin","HD":10,"PAGE":109,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":45}],
"terrains":[{"ID":6},{"ID":11},{"ID":13},{"ID":1},{"ID":4},{"ID":8},{"ID":10},{"ID":5}],
"types":[{"ID":9}],
"SingleFrequency":2},
{"ID":183,"Name":"Feulk","HD":10,"PAGE":78,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":17},{"ID":22}],
"terrains":[{"ID":9}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":302,"Name":"Firedrake","HD":3,"PAGE":145,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":44},{"ID":20}],
"terrains":[{"ID":3},{"ID":1},{"ID":4}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":320,"Name":"Flail Snail","HD":5,"PAGE":146,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":5},{"ID":8}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":86,"Name":"Flesh Lord","HD":16,"PAGE":72,
"source":{"ID":2,"Name":"Tome of the Unclean 1st Printing","ShortName":"ToU"},
"qualities":[{"ID":3},{"ID":22},{"ID":26},{"ID":32}],
"terrains":[{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":1},
{"ID":352,"Name":"Flind","HD":2,"PAGE":147,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21},{"ID":45}],
"terrains":[{"ID":14},{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":4},{"ID":8},{"ID":5}],
"types":[{"ID":10}],
"SingleFrequency":2},
{"ID":137,"Name":"Forsaken","HD":7,"PAGE":81,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":22}],
"terrains":[{"ID":1},{"ID":3},{"ID":4},{"ID":5},{"ID":6},{"ID":7},{"ID":8},{"ID":9}],
"types":[{"ID":16}],
"SingleFrequency":3},
{"ID":205,"Name":"Fox Bat, Giant","HD":3,"PAGE":10,
"source":{"ID":6,"Name":"Basic Fantasy Field Guide","ShortName":"BFFG"},
"qualities":[{"ID":22}],
"terrains":[{"ID":1}],
"types":[{"ID":2}],
"SingleFrequency":1},
{"ID":154,"Name":"Frog, Giant","HD":2,"PAGE":149,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21},{"ID":7}],
"terrains":[{"ID":9},{"ID":1},{"ID":8}],
"types":[{"ID":17}],
"SingleFrequency":1},
{"ID":113,"Name":"Frost Men","HD":4,"PAGE":149,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":6},{"ID":11},{"ID":10}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":140,"Name":"Frost Ogre","HD":3,"PAGE":121,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":22},{"ID":45}],
"terrains":[{"ID":6},{"ID":4}],
"types":[{"ID":9}],
"SingleFrequency":1},
{"ID":155,"Name":"Frost Worm","HD":14,"PAGE":150,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":36},{"ID":22}],
"terrains":[{"ID":6}],
"types":null,"SingleFrequency":1},
{"ID":21,"Name":"Fungus, Violet","HD":2,"PAGE":150,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":11},{"ID":9},{"ID":1},{"ID":8},{"ID":5}],
"types":[{"ID":14}],
"SingleFrequency":1},
{"ID":22,"Name":"Gargoyle","HD":5,"PAGE":152,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":4},{"ID":9}],
"types":[{"ID":12}],
"SingleFrequency":2},
{"ID":156,"Name":"Gelatinous Cube","HD":4,"PAGE":152,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":11},{"ID":10},{"ID":5}],
"types":[{"ID":13}],
"SingleFrequency":2},
{"ID":64,"Name":"Ghast","HD":4,"PAGE":155,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":6},{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":1},{"ID":4},{"ID":8},{"ID":10},{"ID":5},{"ID":14},{"ID":13}],
"types":[{"ID":16}],
"SingleFrequency":2},
{"ID":65,"Name":"Ghost","HD":10,"PAGE":156,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":3},{"ID":11},{"ID":7},{"ID":10},{"ID":5}],
"types":[{"ID":16}],
"SingleFrequency":3},
{"ID":66,"Name":"Ghoul","HD":2,"PAGE":156,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":1},{"ID":4},{"ID":8},{"ID":10},{"ID":14},{"ID":6}],
"types":[{"ID":16}],
"SingleFrequency":1},
{"ID":25,"Name":"Giant","HD":9,"PAGE":159,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":9},{"ID":7},{"ID":13},{"ID":4},{"ID":6},{"ID":14},{"ID":8},{"ID":2},{"ID":12},{"ID":1},{"ID":3},{"ID":15}],
"types":[{"ID":9}],
"SingleFrequency":1},
{"ID":27,"Name":"Gibbering Mouther","HD":4,"PAGE":162,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":11},{"ID":10},{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":3},
{"ID":114,"Name":"Gig (Frog Man)","HD":1,"PAGE":162,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":1},{"ID":8}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":28,"Name":"Gnoll","HD":2,"PAGE":163,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":45}],
"terrains":[{"ID":6},{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":8},{"ID":10},{"ID":5}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":29,"Name":"Goblin","HD":1,"PAGE":164,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20},{"ID":45}],
"terrains":[{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":8},{"ID":10},{"ID":5}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":30,"Name":"Golem","HD":10,"PAGE":164,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":45}],
"terrains":[{"ID":6},{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":1},{"ID":4},{"ID":8},{"ID":10},{"ID":5}],
"types":[{"ID":4}],
"SingleFrequency":2},
{"ID":115,"Name":"Gorgimera","HD":10,"PAGE":167,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":4},{"ID":9}],
"types":[{"ID":11}],
"SingleFrequency":3},
{"ID":321,"Name":"Gorilla Bear","HD":4,"PAGE":168,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":1},{"ID":9}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":40,"Name":"Gray Ooze","HD":3,"PAGE":238,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":11},{"ID":10},{"ID":5}],
"types":[{"ID":13}],
"SingleFrequency":2},
{"ID":290,"Name":"Gray Render","HD":10,"PAGE":112,
"source":{"ID":14,"Name":"D&D 3e Monster Manual - First Printing","ShortName":"MM3"},
"qualities":[{"ID":22}],
"terrains":[{"ID":9},{"ID":7}],
"types":[{"ID":3}],
"SingleFrequency":1},
{"ID":193,"Name":"Green Slime","HD":4,"PAGE":169,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":11},{"ID":9},{"ID":8},{"ID":10}],
"types":[{"ID":13}],
"SingleFrequency":1},
{"ID":256,"Name":"Grell","HD":8,"PAGE":172,
"source":{"ID":10,"Name":"Dungeons & Dragons Monster Manual 5e","ShortName":"MM"},
"qualities":[{"ID":4},{"ID":21}],
"terrains":[{"ID":11},{"ID":10},{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":3},
{"ID":257,"Name":"Grick","HD":8,"PAGE":112,
"source":{"ID":14,"Name":"D&D 3e Monster Manual - First Printing","ShortName":"MM3"},
"qualities":[{"ID":22}],
"terrains":[{"ID":5},{"ID":9}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":316,"Name":"Griffon","HD":7,"PAGE":170,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":4}],
"terrains":[{"ID":4},{"ID":7}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":291,"Name":"Grimlock","HD":2,"PAGE":114,
"source":{"ID":14,"Name":"D&D 3e Monster Manual - First Printing","ShortName":"MM3"},
"qualities":[{"ID":21},{"ID":45}],
"terrains":[{"ID":4},{"ID":5}],
"types":[{"ID":12}],
"SingleFrequency":2},
{"ID":116,"Name":"Gromm","HD":5,"PAGE":170,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":4},{"ID":22}],
"terrains":[{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":170,"Name":"Grue","HD":4,"PAGE":170,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":31,"Name":"Hag","HD":8,"PAGE":172,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":1},{"ID":5},{"ID":8},{"ID":9},{"ID":14},{"ID":15}],
"types":[{"ID":10}],
"SingleFrequency":2},
{"ID":117,"Name":"Hangman's Tree","HD":6,"PAGE":175,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":9},{"ID":7},{"ID":13},{"ID":4}],
"types":[{"ID":14}],
"SingleFrequency":1},
{"ID":32,"Name":"Harpy","HD":3,"PAGE":175,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":9},{"ID":13}],
"types":[{"ID":10}],
"SingleFrequency":2},
{"ID":303,"Name":"Haubui","HD":2,"PAGE":176,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":37},{"ID":21}],
"terrains":[{"ID":10}],
"types":[{"ID":16}],
"SingleFrequency":1},
{"ID":67,"Name":"Haunt","HD":5,"PAGE":176,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":6},{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":1},{"ID":4},{"ID":8},{"ID":10},{"ID":5}],
"types":[{"ID":16}],
"SingleFrequency":2},
{"ID":194,"Name":"Hellhound","HD":6,"PAGE":178,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":37},{"ID":21}],
"terrains":[{"ID":12},{"ID":4}],
"types":[{"ID":7}],
"SingleFrequency":2},
{"ID":348,"Name":"Hippogriff","HD":3,"PAGE":179,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":4},{"ID":22}],
"terrains":[{"ID":4},{"ID":13},{"ID":3},{"ID":9},{"ID":7}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":33,"Name":"Hobgoblin","HD":1,"PAGE":180,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21},{"ID":45}],
"terrains":[{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":8},{"ID":10},{"ID":5}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":157,"Name":"Homunculus","HD":2,"PAGE":181,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":4},{"ID":20}],
"terrains":[{"ID":12}],
"types":[{"ID":4}],
"SingleFrequency":2},
{"ID":172,"Name":"Hook Fiend","HD":5,"PAGE":182,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":118,"Name":"Huecuva","HD":4,"PAGE":183,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":1},{"ID":3},{"ID":4},{"ID":5},{"ID":6},{"ID":7},{"ID":8},{"ID":9}],
"types":[{"ID":16}],
"SingleFrequency":3},
{"ID":184,"Name":"Hulen","HD":7,"PAGE":94,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":4},{"ID":22}],
"terrains":[{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":1},
{"ID":34,"Name":"Hydra","HD":10,"PAGE":185,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":8}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":195,"Name":"Ice Hound","HD":6,"PAGE":66,
"source":{"ID":1,"Name":"Monsters and Treasure 4th Printing","ShortName":"M&T4"},
"qualities":[{"ID":37},{"ID":21}],
"terrains":[{"ID":12}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":138,"Name":"Ice Rounder","HD":8,"PAGE":96,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":22}],
"terrains":[{"ID":6}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":80,"Name":"Iltgallo","HD":6,"PAGE":30,
"source":{"ID":2,"Name":"Tome of the Unclean 1st Printing","ShortName":"ToU"},
"qualities":[{"ID":2},{"ID":22}],
"terrains":[{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":3},
{"ID":87,"Name":"Imp","HD":1,"PAGE":187,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":3},{"ID":20}],
"terrains":[{"ID":11},{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":1},
{"ID":120,"Name":"Insectus","HD":6,"PAGE":187,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":9},{"ID":7},{"ID":13}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":196,"Name":"Invisible Stalker","HD":8,"PAGE":188,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":37},{"ID":22}],
"terrains":[{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":2},
{"ID":158,"Name":"Jackal","HD":2,"PAGE":189,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":3},{"ID":7}],
"types":[{"ID":2}],
"SingleFrequency":1},
{"ID":341,"Name":"Jaculi","HD":1,"PAGE":190,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20}],
"terrains":[{"ID":1},{"ID":9},{"ID":8}],
"types":[{"ID":3}],
"SingleFrequency":1},
{"ID":278,"Name":"Jarim","HD":1,"PAGE":190,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20}],
"terrains":[{"ID":13},{"ID":4},{"ID":5}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":311,"Name":"Kamadan","HD":4,"PAGE":191,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":9},{"ID":1}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":88,"Name":"Karnulch","HD":10,"PAGE":81,
"source":{"ID":2,"Name":"Tome of the Unclean 1st Printing","ShortName":"ToU"},
"qualities":[{"ID":3},{"ID":22},{"ID":26},{"ID":32}],
"terrains":[{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":3},
{"ID":185,"Name":"Kavrun Hound","HD":6,"PAGE":104,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":38},{"ID":21}],
"terrains":[{"ID":9},{"ID":1},{"ID":8},{"ID":5}],
"types":[{"ID":7}],
"SingleFrequency":1},
{"ID":294,"Name":"Kech","HD":5,"PAGE":192,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":17},{"ID":21}],
"terrains":[{"ID":9},{"ID":1}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":304,"Name":"Ketta","HD":3,"PAGE":193,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":12},{"ID":8}],
"types":[{"ID":3}],
"SingleFrequency":1},
{"ID":35,"Name":"Kobold","HD":1,"PAGE":195,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20},{"ID":45}],
"terrains":[{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":8},{"ID":10},{"ID":5},{"ID":6},{"ID":14},{"ID":4}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":312,"Name":"Koschei","HD":3,"PAGE":197,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":37},{"ID":21}],
"terrains":[{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":12},{"ID":8},{"ID":10}],
"types":[{"ID":7}],
"SingleFrequency":1},
{"ID":68,"Name":"Lich","HD":18,"PAGE":203,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21},{"ID":26}],
"terrains":[{"ID":11},{"ID":10},{"ID":5}],
"types":[{"ID":16}],
"SingleFrequency":3},
{"ID":210,"Name":"Linnorm","HD":7,"PAGE":47,
"source":{"ID":6,"Name":"Basic Fantasy Field Guide","ShortName":"BFFG"},
"qualities":[{"ID":37},{"ID":44},{"ID":22}],
"terrains":[{"ID":11},{"ID":5}],
"types":[{"ID":5}],
"SingleFrequency":2},
{"ID":197,"Name":"Living Statue","HD":4,"PAGE":100,
"source":{"ID":5,"Name":"Basic Fantasy Core Rulebook 3rd Edition","ShortName":"BF"},
"qualities":[{"ID":37},{"ID":21},{"ID":45}],
"terrains":[{"ID":6},{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":1},{"ID":4},{"ID":8},{"ID":10},{"ID":5}],
"types":[{"ID":4}],
"SingleFrequency":1},
{"ID":159,"Name":"Lizard, Giant","HD":4,"PAGE":205,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":3},{"ID":9},{"ID":1},{"ID":14}],
"types":[{"ID":2}],
"SingleFrequency":2},
{"ID":36,"Name":"Lizardfolk","HD":2,"PAGE":205,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21},{"ID":45}],
"terrains":[{"ID":1},{"ID":8}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":121,"Name":"Lizardfolk Lord","HD":8,"PAGE":205,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":26},{"ID":38},{"ID":22}],
"terrains":[{"ID":1},{"ID":8}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":173,"Name":"Mantari","HD":1,"PAGE":215,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":8}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":37,"Name":"Manticore","HD":6,"PAGE":216,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":9},{"ID":7},{"ID":8},{"ID":6},{"ID":14},{"ID":13},{"ID":4}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":122,"Name":"Margoyle","HD":6,"PAGE":217,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":4},{"ID":5}],
"types":[{"ID":12}],
"SingleFrequency":2},
{"ID":305,"Name":"Mennotal","HD":4,"PAGE":218,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":5}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":174,"Name":"Merrow","HD":4,"PAGE":219,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":7}],
"terrains":[{"ID":2}],
"types":[{"ID":9}],
"SingleFrequency":1},
{"ID":331,"Name":"Mimic","HD":7,"PAGE":220,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":37}],
"terrains":[{"ID":10},{"ID":11}],
"types":[{"ID":1}],
"SingleFrequency":3},
{"ID":160,"Name":"Minotaur","HD":7,"PAGE":221,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":26},{"ID":22}],
"terrains":[{"ID":11}],
"types":[{"ID":9}],
"SingleFrequency":2},
{"ID":89,"Name":"Mongrel","HD":5,"PAGE":94,
"source":{"ID":2,"Name":"Tome of the Unclean 1st Printing","ShortName":"ToU"},
"qualities":[{"ID":3},{"ID":22}],
"terrains":[{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":2},
{"ID":343,"Name":"Mosquito, Giant","HD":1,"PAGE":49,
"source":{"ID":6,"Name":"Basic Fantasy Field Guide","ShortName":"BFFG"},
"qualities":[{"ID":4}],
"terrains":[{"ID":14},{"ID":3},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":15},{"ID":8},{"ID":5}],
"types":[{"ID":17}],
"SingleFrequency":1},
{"ID":139,"Name":"Moundule","HD":9,"PAGE":116,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":22}],
"terrains":[{"ID":8}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":344,"Name":"Muck Dweller","HD":1,"PAGE":223,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20}],
"terrains":[{"ID":8}],
"types":[{"ID":3}],
"SingleFrequency":1},
{"ID":69,"Name":"Mummy","HD":7,"PAGE":224,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":11},{"ID":10},{"ID":3}],
"types":[{"ID":16}],
"SingleFrequency":1},
{"ID":286,"Name":"Naga","HD":9,"PAGE":227,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":26},{"ID":37},{"ID":22},{"ID":7}],
"terrains":[{"ID":6},{"ID":11},{"ID":12},{"ID":10},{"ID":2},{"ID":3},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":4},{"ID":8},{"ID":5},{"ID":14},{"ID":15}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":175,"Name":"Necrophidius","HD":3,"PAGE":231,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":37},{"ID":22}],
"terrains":[{"ID":12}],
"types":[{"ID":4}],
"SingleFrequency":3},
{"ID":123,"Name":"Needler","HD":3,"PAGE":231,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":9}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":176,"Name":"Nomore'","HD":1,"PAGE":235,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20},{"ID":45}],
"terrains":[{"ID":3},{"ID":7},{"ID":1},{"ID":4},{"ID":8}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":90,"Name":"Nupperibo","HD":3,"PAGE":98,
"source":{"ID":2,"Name":"Tome of the Unclean 1st Printing","ShortName":"ToU"},
"qualities":[{"ID":3},{"ID":21}],
"terrains":[{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":3},
{"ID":41,"Name":"Ochre Jelly","HD":6,"PAGE":238,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":11},{"ID":10},{"ID":5},{"ID":8}],
"types":[{"ID":13}],
"SingleFrequency":1},
{"ID":39,"Name":"Ogre","HD":4,"PAGE":236,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":45}],
"terrains":[{"ID":14},{"ID":3},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":4},{"ID":8}],
"types":[{"ID":9}],
"SingleFrequency":2},
{"ID":325,"Name":"Ogrerat","HD":3,"PAGE":237,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20},{"ID":36}],
"terrains":[{"ID":5}],
"types":[{"ID":3}],
"SingleFrequency":2},
{"ID":124,"Name":"Ogrillon","HD":2,"PAGE":237,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21},{"ID":45}],
"terrains":[{"ID":9},{"ID":7},{"ID":13},{"ID":8},{"ID":4},{"ID":1},{"ID":3},{"ID":14},{"ID":15}],
"types":[{"ID":10}],
"SingleFrequency":2},
{"ID":177,"Name":"Ophidian","HD":4,"PAGE":239,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":1}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":186,"Name":"Orbut","HD":2,"PAGE":124,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":22}],
"terrains":[{"ID":11},{"ID":10}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":42,"Name":"Orc","HD":1,"PAGE":239,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":8},{"ID":10},{"ID":5},{"ID":6},{"ID":4}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":43,"Name":"Otyugh","HD":6,"PAGE":241,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":11},{"ID":10},{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":3},
{"ID":44,"Name":"Owlbear","HD":5,"PAGE":242,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":45}],
"terrains":[{"ID":9}],
"types":[{"ID":3}],
"SingleFrequency":2},
{"ID":81,"Name":"Paralyte","HD":4,"PAGE":41,
"source":{"ID":2,"Name":"Tome of the Unclean 1st Printing","ShortName":"ToU"},
"qualities":[{"ID":2},{"ID":20}],
"terrains":[{"ID":12},{"ID":10}],
"types":[{"ID":7}],
"SingleFrequency":2},
{"ID":125,"Name":"Perrun","HD":1,"PAGE":246,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":4},{"ID":20}],
"terrains":[{"ID":3}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":126,"Name":"Piercer","HD":3,"PAGE":247,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":17},{"ID":21}],
"terrains":[{"ID":5}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":53,"Name":"Pixie","HD":1,"PAGE":153,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20}],
"terrains":[{"ID":9}],
"types":[{"ID":8}],
"SingleFrequency":1},
{"ID":332,"Name":"Psoglav","HD":5,"PAGE":251,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":45},{"ID":21}],
"terrains":[{"ID":5},{"ID":11},{"ID":10}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":45,"Name":"Purple Worm","HD":15,"PAGE":252,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":36},{"ID":22}],
"terrains":[{"ID":3},{"ID":4},{"ID":5}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":314,"Name":"Quaggoth","HD":6,"PAGE":256,
"source":{"ID":10,"Name":"Dungeons & Dragons Monster Manual 5e","ShortName":"MM"},
"qualities":[{"ID":45}],
"terrains":[{"ID":5}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":82,"Name":"Quasit","HD":1,"PAGE":254,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":2},{"ID":4},{"ID":20}],
"terrains":[{"ID":12}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":187,"Name":"Quil","HD":1,"PAGE":132,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":21}],
"terrains":[{"ID":11},{"ID":10},{"ID":5}],
"types":[{"ID":17}],
"SingleFrequency":1},
{"ID":46,"Name":"Rat, Giant","HD":1,"PAGE":255,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20}],
"terrains":[{"ID":9},{"ID":1},{"ID":8},{"ID":5}],
"types":[{"ID":17}],
"SingleFrequency":1},
{"ID":162,"Name":"Remorhaz","HD":7,"PAGE":257,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":6},{"ID":5}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":91,"Name":"Rithkin","HD":2,"PAGE":106,
"source":{"ID":2,"Name":"Tome of the Unclean 1st Printing","ShortName":"ToU"},
"qualities":[{"ID":3},{"ID":17},{"ID":21}],
"terrains":[{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":1},
{"ID":339,"Name":"Rock Hound","HD":5,"PAGE":168,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":21},{"ID":22}],
"terrains":[{"ID":13},{"ID":4},{"ID":9}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":307,"Name":"Rock Reptile","HD":3,"PAGE":259,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20}],
"terrains":[{"ID":5}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":47,"Name":"Roper","HD":7,"PAGE":259,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":17},{"ID":22}],
"terrains":[{"ID":5}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":326,"Name":"Ruel","HD":2,"PAGE":260,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":1}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":333,"Name":"Russet Mold","HD":5,"PAGE":261,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":27},{"ID":21}],
"terrains":[{"ID":9},{"ID":8},{"ID":5},{"ID":1}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":48,"Name":"Rust Monster","HD":5,"PAGE":262,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":142,"Name":"Saber-tooth Tiger","HD":10,"PAGE":136,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":22}],
"terrains":[{"ID":6},{"ID":9},{"ID":13},{"ID":1},{"ID":4},{"ID":8}],
"types":[{"ID":2}],
"SingleFrequency":1},
{"ID":49,"Name":"Sahuagin","HD":2,"PAGE":262,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":7},{"ID":21}],
"terrains":[{"ID":2},{"ID":14},{"ID":15}],
"types":[{"ID":10}],
"SingleFrequency":2},
{"ID":353,"Name":"Salamander","HD":5,"PAGE":263,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":37},{"ID":26},{"ID":22},{"ID":44}],
"terrains":[{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":3},
{"ID":179,"Name":"Sandling","HD":4,"PAGE":264,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":3}],
"types":[{"ID":7}],
"SingleFrequency":2},
{"ID":127,"Name":"Sandman","HD":4,"PAGE":265,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":3}],
"types":[{"ID":7}],
"SingleFrequency":2},
{"ID":92,"Name":"Sauld","HD":3,"PAGE":106,
"source":{"ID":2,"Name":"Tome of the Unclean 1st Printing","ShortName":"ToU"},
"qualities":[{"ID":3},{"ID":17},{"ID":21}],
"terrains":[{"ID":11},{"ID":12},{"ID":10},{"ID":5}],
"types":[{"ID":7}],
"SingleFrequency":1},
{"ID":198,"Name":"Scorpion, Giant","HD":4,"PAGE":114,
"source":{"ID":5,"Name":"Basic Fantasy Core Rulebook 3rd Edition","ShortName":"BF"},
"qualities":[{"ID":22},{"ID":21}],
"terrains":[{"ID":3},{"ID":5}],
"types":[{"ID":17}],
"SingleFrequency":1},
{"ID":50,"Name":"Screecher","HD":3,"PAGE":266,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21},{"ID":25}],
"terrains":[{"ID":11},{"ID":10},{"ID":5}],
"types":[{"ID":14}],
"SingleFrequency":1},
{"ID":309,"Name":"Scucca","HD":8,"PAGE":267,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":7},{"ID":13},{"ID":10}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":199,"Name":"Sea Serpent","HD":6,"PAGE":114,
"source":{"ID":5,"Name":"Basic Fantasy Core Rulebook 3rd Edition","ShortName":"BF"},
"qualities":[{"ID":22},{"ID":7}],
"terrains":[{"ID":2}],
"types":[{"ID":3}],
"SingleFrequency":1},
{"ID":71,"Name":"Shadow","HD":3,"PAGE":268,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":11},{"ID":10},{"ID":5}],
"types":[{"ID":16}],
"SingleFrequency":1},
{"ID":93,"Name":"Shadow Guardian","HD":1,"PAGE":108,
"source":{"ID":2,"Name":"Tome of the Unclean 1st Printing","ShortName":"ToU"},
"qualities":[{"ID":3},{"ID":6},{"ID":20}],
"terrains":[{"ID":12}],
"types":[{"ID":7}],
"SingleFrequency":1},
{"ID":279,"Name":"Shambling Mound","HD":8,"PAGE":270,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":1},{"ID":8},{"ID":5},{"ID":9}],
"types":[{"ID":14}],
"SingleFrequency":1},
{"ID":129,"Name":"Shelkerow","HD":10,"PAGE":271,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":26}],
"terrains":[{"ID":6},{"ID":3},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":4},{"ID":8},{"ID":5}],
"types":[{"ID":7}],
"SingleFrequency":3},
{"ID":212,"Name":"Shield Guardian","HD":15,"PAGE":66,
"source":{"ID":6,"Name":"Basic Fantasy Field Guide","ShortName":"BFFG"},
"qualities":[{"ID":26},{"ID":37},{"ID":22}],
"terrains":[{"ID":12}],
"types":[{"ID":4}],
"SingleFrequency":1},
{"ID":200,"Name":"Shrieker","HD":3,"PAGE":116,
"source":{"ID":5,"Name":"Basic Fantasy Core Rulebook 3rd Edition","ShortName":"BF"},
"qualities":[{"ID":25},{"ID":20}],
"terrains":[{"ID":11},{"ID":10},{"ID":5}],
"types":[{"ID":14}],
"SingleFrequency":1},
{"ID":73,"Name":"Skeletal Warrior","HD":10,"PAGE":272,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21},{"ID":26}],
"terrains":[{"ID":11},{"ID":10}],
"types":[{"ID":16}],
"SingleFrequency":2},
{"ID":72,"Name":"Skeleton","HD":1,"PAGE":273,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":6},{"ID":14},{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":4},{"ID":8},{"ID":10},{"ID":5}],
"types":[{"ID":16}],
"SingleFrequency":1},
{"ID":328,"Name":"Skohls","HD":4,"PAGE":274,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":13},{"ID":7}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":188,"Name":"Smoke Guardian","HD":2,"PAGE":140,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":37},{"ID":22}],
"terrains":[{"ID":12}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":201,"Name":"Snake, Giant","HD":6,"PAGE":277,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":4},{"ID":8},{"ID":5}],
"types":[{"ID":2}],
"SingleFrequency":1},
{"ID":211,"Name":"Snow Orc","HD":2,"PAGE":54,
"source":{"ID":6,"Name":"Basic Fantasy Field Guide","ShortName":"BFFG"},
"qualities":[{"ID":21},{"ID":45}],
"terrains":[{"ID":6}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":253,"Name":"Spectator","HD":10,"PAGE":30,
"source":{"ID":10,"Name":"Dungeons & Dragons Monster Manual 5e","ShortName":"MM"},
"qualities":[{"ID":4},{"ID":37},{"ID":21}],
"terrains":[{"ID":11},{"ID":12},{"ID":10},{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":74,"Name":"Spectre","HD":7,"PAGE":278,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":11}],
"types":[{"ID":16}],
"SingleFrequency":3},
{"ID":52,"Name":"Spider","HD":3,"PAGE":280,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":3},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":4},{"ID":8},{"ID":5}],
"types":[{"ID":17}],
"SingleFrequency":1},
{"ID":130,"Name":"Squealer","HD":12,"PAGE":281,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":1},{"ID":8},{"ID":9}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":202,"Name":"Stirge","HD":1,"PAGE":281,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":4},{"ID":20}],
"terrains":[{"ID":1},{"ID":8},{"ID":5},{"ID":9},{"ID":13},{"ID":4}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":131,"Name":"Stone Guardian","HD":4,"PAGE":281,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":6},{"ID":3},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":4},{"ID":8},{"ID":5}],
"types":[{"ID":4}],
"SingleFrequency":2},
{"ID":180,"Name":"Stun Jelly","HD":4,"PAGE":282,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":37},{"ID":22}],
"terrains":[{"ID":3},{"ID":10}],
"types":[{"ID":13}],
"SingleFrequency":1},
{"ID":83,"Name":"Succubus","HD":6,"PAGE":43,
"source":{"ID":2,"Name":"Tome of the Unclean 1st Printing","ShortName":"ToU"},
"qualities":[{"ID":26},{"ID":2},{"ID":21}],
"terrains":[{"ID":11},{"ID":10}],
"types":[{"ID":7}],
"SingleFrequency":3},
{"ID":143,"Name":"Suk Tree","HD":8,"PAGE":146,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":22}],
"terrains":[{"ID":7}],
"types":[{"ID":14}],
"SingleFrequency":1},
{"ID":132,"Name":"Tail-Goblins","HD":1,"PAGE":284,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20}],
"terrains":[{"ID":1}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":322,"Name":"Tavis Wyrm","HD":3,"PAGE":286,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":3},{"ID":5}],
"types":[{"ID":7}],
"SingleFrequency":2},
{"ID":292,"Name":"Tendriculos","HD":9,"PAGE":175,
"source":{"ID":14,"Name":"D&D 3e Monster Manual - First Printing","ShortName":"MM3"},
"qualities":[{"ID":22}],
"terrains":[{"ID":9},{"ID":13},{"ID":8}],
"types":[{"ID":14}],
"SingleFrequency":1},
{"ID":203,"Name":"Tentacled Worm","HD":3,"PAGE":120,
"source":{"ID":5,"Name":"Basic Fantasy Core Rulebook 3rd Edition","ShortName":"BF"},
"qualities":[{"ID":22}],
"terrains":[{"ID":11},{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":144,"Name":"Terralip Tree","HD":8,"PAGE":150,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":22}],
"terrains":[{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":8}],
"types":[{"ID":14}],
"SingleFrequency":1},
{"ID":310,"Name":"Thirs","HD":6,"PAGE":288,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20},{"ID":45}],
"terrains":[{"ID":8}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":330,"Name":"Tick, Giant","HD":2,"PAGE":289,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20}],
"terrains":[{"ID":5},{"ID":9},{"ID":8}],
"types":[{"ID":17}],
"SingleFrequency":1},
{"ID":54,"Name":"Tiger/Panther","HD":5,"PAGE":289,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":1},{"ID":4},{"ID":6},{"ID":7},{"ID":8},{"ID":9},{"ID":3},{"ID":13},{"ID":14}],
"types":[{"ID":2}],
"SingleFrequency":1},
{"ID":204,"Name":"Troglodyte","HD":2,"PAGE":291,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":8},{"ID":5}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":56,"Name":"Troll","HD":7,"PAGE":292,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22},{"ID":45}],
"terrains":[{"ID":6},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":4},{"ID":8}],
"types":[{"ID":9}],
"SingleFrequency":2},
{"ID":189,"Name":"Troll Lord","HD":9,"PAGE":151,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":38},{"ID":22},{"ID":45}],
"terrains":[{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":4},{"ID":8}],
"types":[{"ID":9}],
"SingleFrequency":3},
{"ID":293,"Name":"Umberhulk","HD":8,"PAGE":180,
"source":{"ID":14,"Name":"D&D 3e Monster Manual - First Printing","ShortName":"MM3"},
"qualities":[{"ID":22}],
"terrains":[{"ID":5}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":190,"Name":"Ungern","HD":2,"PAGE":156,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":21}],
"terrains":[{"ID":6},{"ID":4}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":57,"Name":"Vampire","HD":8,"PAGE":295,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21},{"ID":26}],
"terrains":[{"ID":11},{"ID":10}],
"types":[{"ID":16}],
"SingleFrequency":3},
{"ID":133,"Name":"Vegepygmy","HD":4,"PAGE":298,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":1},{"ID":8},{"ID":9}],
"types":[{"ID":10}],
"SingleFrequency":1},
{"ID":146,"Name":"Vimnel","HD":4,"PAGE":159,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":4},{"ID":20}],
"terrains":[{"ID":1},{"ID":4},{"ID":7},{"ID":8},{"ID":9}],
"types":[{"ID":1}],
"SingleFrequency":1},
{"ID":284,"Name":"Viyl Beast","HD":5,"PAGE":159,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":21}],
"terrains":[{"ID":9},{"ID":7},{"ID":13},{"ID":1}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":323,"Name":"Volt","HD":2,"PAGE":300,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20},{"ID":4}],
"terrains":[{"ID":5},{"ID":10},{"ID":11}],
"types":[{"ID":11}],
"SingleFrequency":2},
{"ID":147,"Name":"Vordoag","HD":1,"PAGE":160,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":20}],
"terrains":[{"ID":5}],
"types":[{"ID":2}],
"SingleFrequency":1},
{"ID":283,"Name":"Wasp, Giant","HD":3,"PAGE":206,
"source":{"ID":14,"Name":"D&D 3e Monster Manual - First Printing","ShortName":"MM3"},
"qualities":[{"ID":4},{"ID":21}],
"terrains":[{"ID":14},{"ID":3},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":8}],
"types":[{"ID":17}],
"SingleFrequency":1},
{"ID":75,"Name":"Wight","HD":4,"PAGE":301,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":11},{"ID":10},{"ID":8}],
"types":[{"ID":16}],
"SingleFrequency":3},
{"ID":60,"Name":"Winter Wolf","HD":6,"PAGE":303,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":6}],
"types":[{"ID":2}],
"SingleFrequency":1},
{"ID":340,"Name":"Witch Orb","HD":2,"PAGE":164,
"source":{"ID":4,"Name":"Monsters & Treasure of Airdhe 3rd Printing","ShortName":"M&TA"},
"qualities":[{"ID":4},{"ID":20}],
"terrains":[{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":4},{"ID":8},{"ID":5},{"ID":10}],
"types":[{"ID":1}],
"SingleFrequency":2},
{"ID":334,"Name":"Witherstench","HD":2,"PAGE":303,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20}],
"terrains":[{"ID":5},{"ID":9},{"ID":1},{"ID":8},{"ID":11}],
"types":[{"ID":3}],
"SingleFrequency":1},
{"ID":58,"Name":"Wolf","HD":2,"PAGE":302,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20}],
"terrains":[{"ID":6},{"ID":3},{"ID":9},{"ID":7},{"ID":13},{"ID":4}],
"types":[{"ID":2}],
"SingleFrequency":1},
{"ID":59,"Name":"Worg","HD":4,"PAGE":302,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":6},{"ID":3},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":4},{"ID":8}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":76,"Name":"Wraith","HD":5,"PAGE":304,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":11},{"ID":10}],
"types":[{"ID":16}],
"SingleFrequency":3},
{"ID":163,"Name":"Wyvern","HD":7,"PAGE":305,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":4},{"ID":44},{"ID":22}],
"terrains":[{"ID":3},{"ID":7},{"ID":13},{"ID":1}],
"types":[{"ID":5}],
"SingleFrequency":2},
{"ID":61,"Name":"Yellow Mold","HD":1,"PAGE":307,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":20},{"ID":27}],
"terrains":[{"ID":11},{"ID":5}],
"types":[{"ID":14}],
"SingleFrequency":1},
{"ID":134,"Name":"Yellow Musk Creeper","HD":3,"PAGE":307,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":1},{"ID":8},{"ID":9}],
"types":[{"ID":14}],
"SingleFrequency":1},
{"ID":324,"Name":"Yeth Hound","HD":3,"PAGE":308,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":7},{"ID":13}],
"types":[{"ID":7}],
"SingleFrequency":1},
{"ID":265,"Name":"Yeti","HD":5,"PAGE":308,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":22}],
"terrains":[{"ID":6}],
"types":[{"ID":10}],
"SingleFrequency":2},
{"ID":62,"Name":"Yrthak","HD":12,"PAGE":309,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":4},{"ID":22}],
"terrains":[{"ID":3}],
"types":[{"ID":11}],
"SingleFrequency":1},
{"ID":77,"Name":"Zombie","HD":2,"PAGE":310,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":6},{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":8},{"ID":10},{"ID":5}],
"types":[{"ID":16}],
"SingleFrequency":2},
{"ID":78,"Name":"Zombie Monster","HD":3,"PAGE":310,
"source":{"ID":15,"Name":"Monsters and Treasure 5th Printing","ShortName":"M&T"},
"qualities":[{"ID":21}],
"terrains":[{"ID":6},{"ID":3},{"ID":11},{"ID":9},{"ID":7},{"ID":13},{"ID":1},{"ID":8},{"ID":10},{"ID":5}],
"types":[{"ID":16}],
"SingleFrequency":2},
];

var locationdata = [
{"ID":1,"Name":"Jungle"},
{"ID":2,"Name":"Water"},
{"ID":3,"Name":"Desert"},
{"ID":4,"Name":"Mountains"},
{"ID":5,"Name":"Underground"},
{"ID":6,"Name":"Arctic"},
{"ID":7,"Name":"Grasslands"},
{"ID":8,"Name":"Swamp"},
{"ID":9,"Name":"Forest"},
{"ID":10,"Name":"Tomb"},
{"ID":11,"Name":"Dungeon"},
{"ID":12,"Name":"Summoned"},
{"ID":13,"Name":"Hills"},
{"ID":14,"Name":"Coast"},
{"ID":15,"Name":"Lake"}
];

var qualitydata = [
{"ID":2,"Name":"Demon"},
{"ID":3,"Name":"Devil"},
{"ID":4,"Name":"Fly"},
{"ID":6,"Name":"Incorporeal"},
{"ID":7,"Name":"Swim"},
{"ID":17,"Name":"Drop attack"},
{"ID":20,"Name":"Small"},
{"ID":21,"Name":"Medium"},
{"ID":22,"Name":"Large"},
{"ID":25,"Name":"Noisy"},
{"ID":26,"Name":"Boss"},
{"ID":27,"Name":"Germ"},
{"ID":32,"Name":"Greater"},
{"ID":36,"Name":"Burrows"},
{"ID":37,"Name":"Guardian"},
{"ID":38,"Name":"Companion"},
{"ID":40,"Name":"Avian"},
{"ID":41,"Name":"Swarm"},
{"ID":42,"Name":"NPC"},
{"ID":43,"Name":"National"},
{"ID":44,"Name":"Lair"},
{"ID":45,"Name":"Minion"}
];

var typedata = [
{"ID":1,"Name":"Abberation"},
{"ID":2,"Name":"Animal"},
{"ID":3,"Name":"Beast"},
{"ID":4,"Name":"Construct"},
{"ID":5,"Name":"Dragon"},
{"ID":6,"Name":"Elemental"},
{"ID":7,"Name":"Extraplanar"},
{"ID":8,"Name":"Fey"},
{"ID":9,"Name":"Giant"},
{"ID":10,"Name":"Humanoid"},
{"ID":11,"Name":"Magical Beast"},
{"ID":12,"Name":"Monstrous Humanoid"},
{"ID":13,"Name":"Ooze"},
{"ID":14,"Name":"Plant"},
{"ID":15,"Name":"Shapechanger"},
{"ID":16,"Name":"Undead"},
{"ID":17,"Name":"Vermin"}
];

